import { PlayerTile } from './playerTile';

export const PLAYERTILES: PlayerTile[] = [
  { id: 1,
    nick: "Olda",
    alive: true,
    rank: 100,
    hp: 100,
    points: 0,
    def: 0,
    att: 1,
    farm: 0,
    color: '' },
  { id: 2,
    nick: "Stoff",
    alive: true,
    rank: 100,
    hp: 100,
    points: 0,
    def: 1,
    att: 0,
    farm: 0,
    color: '' },
  { id: 3,
    nick: "Vita",
    alive: true,
    rank: 100,
    hp: 100,
    points: 0,
    def: 0,
    att: 0,
    farm: 1,
    color: '' },
  { id: 4,
    nick: "Svondi",
    alive: true,
    rank: 100,
    hp: 100,
    points: 0,
    def: 0,
    att: 0,
    farm: 0,
    color: '' },
  { id: 5,
    nick: "Materna",
    alive: true,
    rank: 100,
    hp: 100,
    points: 0,
    def: 2,
    att: 1,
    farm: 0,
    color: '' },
  { id: 6,
    nick: "Lejsek",
    alive: true,
    rank: 100,
    hp: 100,
    points: 0,
    def: 0,
    att: 1,
    farm: 3,
    color: '' },    
];