import { PlayerTile } from './playerTile';

export const PLAYERTILES: PlayerTile[] = [
  {
    "id": 0,
    "nick": "Lewis",
    "alive": false,
    "hp": 94,
    "power": 1714,
    "def": 24,
    "att": 13,
    "farm": 9,
    "color": ""
  },
  {
    "id": 1,
    "nick": "Cote",
    "alive": false,
    "hp": 64,
    "power": 918,
    "def": 7,
    "att": 11,
    "farm": 13,
    "color": ""
  },
  {
    "id": 2,
    "nick": "Edith",
    "alive": true,
    "hp": 96,
    "power": 1702,
    "def": 12,
    "att": 23,
    "farm": 19,
    "color": ""
  },
  {
    "id": 3,
    "nick": "Finch",
    "alive": false,
    "hp": 98,
    "power": 475,
    "def": 2,
    "att": 27,
    "farm": 13,
    "color": ""
  },
  {
    "id": 4,
    "nick": "Rita",
    "alive": false,
    "hp": 85,
    "power": 210,
    "def": 25,
    "att": 7,
    "farm": 1,
    "color": ""
  },
  {
    "id": 5,
    "nick": "Carol",
    "alive": true,
    "hp": 89,
    "power": 600,
    "def": 26,
    "att": 25,
    "farm": 5,
    "color": ""
  },
  {
    "id": 6,
    "nick": "Woodard",
    "alive": false,
    "hp": 86,
    "power": 925,
    "def": 3,
    "att": 1,
    "farm": 13,
    "color": ""
  },
  {
    "id": 7,
    "nick": "Pickett",
    "alive": false,
    "hp": 96,
    "power": 1171,
    "def": 25,
    "att": 8,
    "farm": 2,
    "color": ""
  },
  {
    "id": 8,
    "nick": "Rogers",
    "alive": true,
    "hp": 60,
    "power": 1506,
    "def": 27,
    "att": 28,
    "farm": 27,
    "color": ""
  },
  {
    "id": 9,
    "nick": "Owen",
    "alive": false,
    "hp": 83,
    "power": 911,
    "def": 22,
    "att": 25,
    "farm": 27,
    "color": ""
  },
  {
    "id": 10,
    "nick": "Leann",
    "alive": true,
    "hp": 68,
    "power": 243,
    "def": 29,
    "att": 12,
    "farm": 5,
    "color": ""
  },
  {
    "id": 11,
    "nick": "Beulah",
    "alive": false,
    "hp": 50,
    "power": 368,
    "def": 13,
    "att": 4,
    "farm": 15,
    "color": ""
  },
  {
    "id": 12,
    "nick": "Terry",
    "alive": true,
    "hp": 88,
    "power": 1820,
    "def": 7,
    "att": 27,
    "farm": 21,
    "color": ""
  },
  {
    "id": 13,
    "nick": "Wanda",
    "alive": false,
    "hp": 44,
    "power": 696,
    "def": 12,
    "att": 9,
    "farm": 16,
    "color": ""
  },
  {
    "id": 14,
    "nick": "Bishop",
    "alive": false,
    "hp": 83,
    "power": 1169,
    "def": 8,
    "att": 21,
    "farm": 30,
    "color": ""
  },
  {
    "id": 15,
    "nick": "Jana",
    "alive": true,
    "hp": 72,
    "power": 1215,
    "def": 8,
    "att": 15,
    "farm": 20,
    "color": ""
  },
  {
    "id": 16,
    "nick": "Angelia",
    "alive": false,
    "hp": 71,
    "power": 1208,
    "def": 16,
    "att": 8,
    "farm": 20,
    "color": ""
  },
  {
    "id": 17,
    "nick": "Watts",
    "alive": true,
    "hp": 57,
    "power": 980,
    "def": 19,
    "att": 3,
    "farm": 16,
    "color": ""
  },
  {
    "id": 18,
    "nick": "Gibbs",
    "alive": true,
    "hp": 58,
    "power": 86,
    "def": 14,
    "att": 0,
    "farm": 0,
    "color": ""
  },
  {
    "id": 19,
    "nick": "Penny",
    "alive": true,
    "hp": 58,
    "power": 1490,
    "def": 26,
    "att": 24,
    "farm": 3,
    "color": ""
  },
  {
    "id": 20,
    "nick": "Jefferson",
    "alive": true,
    "hp": 76,
    "power": 192,
    "def": 18,
    "att": 30,
    "farm": 11,
    "color": ""
  },
  {
    "id": 21,
    "nick": "Cassie",
    "alive": true,
    "hp": 32,
    "power": 1675,
    "def": 5,
    "att": 15,
    "farm": 11,
    "color": ""
  },
  {
    "id": 22,
    "nick": "Hallie",
    "alive": true,
    "hp": 90,
    "power": 434,
    "def": 29,
    "att": 0,
    "farm": 12,
    "color": ""
  },
  {
    "id": 23,
    "nick": "Lilian",
    "alive": true,
    "hp": 64,
    "power": 645,
    "def": 1,
    "att": 19,
    "farm": 7,
    "color": ""
  },
  {
    "id": 24,
    "nick": "French",
    "alive": true,
    "hp": 72,
    "power": 1530,
    "def": 3,
    "att": 22,
    "farm": 4,
    "color": ""
  },
  {
    "id": 25,
    "nick": "Rachel",
    "alive": false,
    "hp": 81,
    "power": 86,
    "def": 4,
    "att": 2,
    "farm": 1,
    "color": ""
  },
  {
    "id": 26,
    "nick": "Kristy",
    "alive": false,
    "hp": 39,
    "power": 1989,
    "def": 16,
    "att": 29,
    "farm": 19,
    "color": ""
  },
  {
    "id": 27,
    "nick": "Craft",
    "alive": true,
    "hp": 57,
    "power": 1330,
    "def": 30,
    "att": 28,
    "farm": 9,
    "color": ""
  },
  {
    "id": 28,
    "nick": "Adela",
    "alive": true,
    "hp": 83,
    "power": 1311,
    "def": 25,
    "att": 8,
    "farm": 21,
    "color": ""
  },
  {
    "id": 29,
    "nick": "Hill",
    "alive": false,
    "hp": 51,
    "power": 1391,
    "def": 6,
    "att": 3,
    "farm": 17,
    "color": ""
  },
  {
    "id": 30,
    "nick": "Burnett",
    "alive": true,
    "hp": 62,
    "power": 1928,
    "def": 8,
    "att": 19,
    "farm": 20,
    "color": ""
  },
  {
    "id": 31,
    "nick": "Sally",
    "alive": false,
    "hp": 31,
    "power": 864,
    "def": 14,
    "att": 5,
    "farm": 11,
    "color": ""
  },
  {
    "id": 32,
    "nick": "Kara",
    "alive": false,
    "hp": 80,
    "power": 1672,
    "def": 1,
    "att": 3,
    "farm": 15,
    "color": ""
  },
  {
    "id": 33,
    "nick": "Mendez",
    "alive": false,
    "hp": 35,
    "power": 683,
    "def": 16,
    "att": 28,
    "farm": 21,
    "color": ""
  },
  {
    "id": 34,
    "nick": "Steele",
    "alive": true,
    "hp": 99,
    "power": 1990,
    "def": 22,
    "att": 0,
    "farm": 6,
    "color": ""
  },
  {
    "id": 35,
    "nick": "Raymond",
    "alive": true,
    "hp": 42,
    "power": 80,
    "def": 20,
    "att": 2,
    "farm": 1,
    "color": ""
  },
  {
    "id": 36,
    "nick": "Travis",
    "alive": false,
    "hp": 87,
    "power": 449,
    "def": 17,
    "att": 28,
    "farm": 20,
    "color": ""
  },
  {
    "id": 37,
    "nick": "Bernard",
    "alive": false,
    "hp": 30,
    "power": 1389,
    "def": 9,
    "att": 24,
    "farm": 7,
    "color": ""
  },
  {
    "id": 38,
    "nick": "Casandra",
    "alive": true,
    "hp": 85,
    "power": 919,
    "def": 25,
    "att": 7,
    "farm": 9,
    "color": ""
  },
  {
    "id": 39,
    "nick": "Richmond",
    "alive": false,
    "hp": 35,
    "power": 487,
    "def": 21,
    "att": 4,
    "farm": 20,
    "color": ""
  },
  {
    "id": 40,
    "nick": "Haley",
    "alive": false,
    "hp": 93,
    "power": 602,
    "def": 22,
    "att": 26,
    "farm": 1,
    "color": ""
  },
  {
    "id": 41,
    "nick": "Karina",
    "alive": true,
    "hp": 74,
    "power": 57,
    "def": 11,
    "att": 6,
    "farm": 26,
    "color": ""
  },
  {
    "id": 42,
    "nick": "Walsh",
    "alive": true,
    "hp": 34,
    "power": 1704,
    "def": 17,
    "att": 21,
    "farm": 22,
    "color": ""
  },
  {
    "id": 43,
    "nick": "Castro",
    "alive": true,
    "hp": 39,
    "power": 692,
    "def": 27,
    "att": 9,
    "farm": 3,
    "color": ""
  },
  {
    "id": 44,
    "nick": "Alisha",
    "alive": true,
    "hp": 95,
    "power": 506,
    "def": 24,
    "att": 29,
    "farm": 15,
    "color": ""
  },
  {
    "id": 45,
    "nick": "Dolly",
    "alive": true,
    "hp": 46,
    "power": 1894,
    "def": 0,
    "att": 17,
    "farm": 29,
    "color": ""
  },
  {
    "id": 46,
    "nick": "Sara",
    "alive": false,
    "hp": 83,
    "power": 777,
    "def": 19,
    "att": 16,
    "farm": 24,
    "color": ""
  },
  {
    "id": 47,
    "nick": "Verna",
    "alive": true,
    "hp": 99,
    "power": 1884,
    "def": 13,
    "att": 20,
    "farm": 9,
    "color": ""
  },
  {
    "id": 48,
    "nick": "Ethel",
    "alive": false,
    "hp": 50,
    "power": 1437,
    "def": 19,
    "att": 10,
    "farm": 0,
    "color": ""
  },
  {
    "id": 49,
    "nick": "Michele",
    "alive": false,
    "hp": 32,
    "power": 200,
    "def": 23,
    "att": 12,
    "farm": 20,
    "color": ""
  },
  {
    "id": 50,
    "nick": "Edwina",
    "alive": false,
    "hp": 31,
    "power": 1729,
    "def": 17,
    "att": 18,
    "farm": 20,
    "color": ""
  },
  {
    "id": 51,
    "nick": "Sherry",
    "alive": false,
    "hp": 96,
    "power": 526,
    "def": 3,
    "att": 20,
    "farm": 16,
    "color": ""
  },
  {
    "id": 52,
    "nick": "Roberson",
    "alive": false,
    "hp": 74,
    "power": 336,
    "def": 5,
    "att": 7,
    "farm": 16,
    "color": ""
  },
  {
    "id": 53,
    "nick": "Taylor",
    "alive": false,
    "hp": 97,
    "power": 1453,
    "def": 30,
    "att": 11,
    "farm": 16,
    "color": ""
  },
  {
    "id": 54,
    "nick": "Kenya",
    "alive": true,
    "hp": 74,
    "power": 1703,
    "def": 30,
    "att": 13,
    "farm": 26,
    "color": ""
  },
  {
    "id": 55,
    "nick": "Georgina",
    "alive": true,
    "hp": 96,
    "power": 1233,
    "def": 15,
    "att": 25,
    "farm": 17,
    "color": ""
  },
  {
    "id": 56,
    "nick": "Pruitt",
    "alive": false,
    "hp": 56,
    "power": 1669,
    "def": 11,
    "att": 1,
    "farm": 12,
    "color": ""
  },
  {
    "id": 57,
    "nick": "Eula",
    "alive": true,
    "hp": 95,
    "power": 953,
    "def": 28,
    "att": 22,
    "farm": 4,
    "color": ""
  },
  {
    "id": 58,
    "nick": "Madeleine",
    "alive": false,
    "hp": 32,
    "power": 600,
    "def": 13,
    "att": 21,
    "farm": 27,
    "color": ""
  },
  {
    "id": 59,
    "nick": "Delaney",
    "alive": false,
    "hp": 75,
    "power": 1021,
    "def": 23,
    "att": 18,
    "farm": 13,
    "color": ""
  },
  {
    "id": 60,
    "nick": "Leon",
    "alive": true,
    "hp": 41,
    "power": 1087,
    "def": 10,
    "att": 24,
    "farm": 2,
    "color": ""
  },
  {
    "id": 61,
    "nick": "Fischer",
    "alive": true,
    "hp": 30,
    "power": 1489,
    "def": 15,
    "att": 9,
    "farm": 12,
    "color": ""
  },
  {
    "id": 62,
    "nick": "Blackwell",
    "alive": true,
    "hp": 49,
    "power": 258,
    "def": 10,
    "att": 26,
    "farm": 24,
    "color": ""
  },
  {
    "id": 63,
    "nick": "Mitchell",
    "alive": false,
    "hp": 42,
    "power": 32,
    "def": 25,
    "att": 20,
    "farm": 26,
    "color": ""
  },
  {
    "id": 64,
    "nick": "Franklin",
    "alive": true,
    "hp": 63,
    "power": 1505,
    "def": 7,
    "att": 6,
    "farm": 20,
    "color": ""
  },
  {
    "id": 65,
    "nick": "Marina",
    "alive": false,
    "hp": 74,
    "power": 1402,
    "def": 25,
    "att": 19,
    "farm": 7,
    "color": ""
  },
  {
    "id": 66,
    "nick": "Carolina",
    "alive": true,
    "hp": 33,
    "power": 1191,
    "def": 23,
    "att": 6,
    "farm": 8,
    "color": ""
  },
  {
    "id": 67,
    "nick": "Latisha",
    "alive": true,
    "hp": 71,
    "power": 141,
    "def": 13,
    "att": 29,
    "farm": 8,
    "color": ""
  },
  {
    "id": 68,
    "nick": "Lora",
    "alive": false,
    "hp": 91,
    "power": 104,
    "def": 25,
    "att": 23,
    "farm": 21,
    "color": ""
  },
  {
    "id": 69,
    "nick": "Reva",
    "alive": true,
    "hp": 90,
    "power": 1189,
    "def": 29,
    "att": 23,
    "farm": 27,
    "color": ""
  },
  {
    "id": 70,
    "nick": "Bauer",
    "alive": false,
    "hp": 93,
    "power": 1585,
    "def": 17,
    "att": 11,
    "farm": 16,
    "color": ""
  },
  {
    "id": 71,
    "nick": "Sarah",
    "alive": true,
    "hp": 37,
    "power": 463,
    "def": 29,
    "att": 13,
    "farm": 27,
    "color": ""
  },
  {
    "id": 72,
    "nick": "Florine",
    "alive": true,
    "hp": 85,
    "power": 1090,
    "def": 22,
    "att": 24,
    "farm": 25,
    "color": ""
  },
  {
    "id": 73,
    "nick": "Lorena",
    "alive": false,
    "hp": 82,
    "power": 1954,
    "def": 6,
    "att": 17,
    "farm": 24,
    "color": ""
  },
  {
    "id": 74,
    "nick": "Josephine",
    "alive": false,
    "hp": 74,
    "power": 1329,
    "def": 0,
    "att": 0,
    "farm": 21,
    "color": ""
  },
  {
    "id": 75,
    "nick": "Middleton",
    "alive": false,
    "hp": 37,
    "power": 881,
    "def": 4,
    "att": 6,
    "farm": 5,
    "color": ""
  },
  {
    "id": 76,
    "nick": "Lindsey",
    "alive": true,
    "hp": 46,
    "power": 804,
    "def": 1,
    "att": 10,
    "farm": 25,
    "color": ""
  },
  {
    "id": 77,
    "nick": "Gracie",
    "alive": true,
    "hp": 97,
    "power": 1680,
    "def": 3,
    "att": 9,
    "farm": 24,
    "color": ""
  },
  {
    "id": 78,
    "nick": "Ines",
    "alive": false,
    "hp": 69,
    "power": 1384,
    "def": 13,
    "att": 28,
    "farm": 6,
    "color": ""
  },
  {
    "id": 79,
    "nick": "Crosby",
    "alive": true,
    "hp": 41,
    "power": 855,
    "def": 7,
    "att": 18,
    "farm": 17,
    "color": ""
  },
  {
    "id": 80,
    "nick": "Monica",
    "alive": true,
    "hp": 81,
    "power": 1686,
    "def": 0,
    "att": 29,
    "farm": 18,
    "color": ""
  },
  {
    "id": 81,
    "nick": "Tiffany",
    "alive": true,
    "hp": 73,
    "power": 1357,
    "def": 26,
    "att": 19,
    "farm": 29,
    "color": ""
  },
  {
    "id": 82,
    "nick": "Latonya",
    "alive": true,
    "hp": 49,
    "power": 1663,
    "def": 26,
    "att": 7,
    "farm": 27,
    "color": ""
  },
  {
    "id": 83,
    "nick": "Kimberly",
    "alive": true,
    "hp": 38,
    "power": 1710,
    "def": 28,
    "att": 21,
    "farm": 3,
    "color": ""
  },
  {
    "id": 84,
    "nick": "Ferrell",
    "alive": true,
    "hp": 87,
    "power": 1809,
    "def": 2,
    "att": 18,
    "farm": 11,
    "color": ""
  },
  {
    "id": 85,
    "nick": "Terra",
    "alive": false,
    "hp": 61,
    "power": 558,
    "def": 9,
    "att": 13,
    "farm": 10,
    "color": ""
  },
  {
    "id": 86,
    "nick": "Jill",
    "alive": false,
    "hp": 63,
    "power": 1328,
    "def": 19,
    "att": 8,
    "farm": 29,
    "color": ""
  },
  {
    "id": 87,
    "nick": "Corina",
    "alive": false,
    "hp": 45,
    "power": 722,
    "def": 30,
    "att": 27,
    "farm": 23,
    "color": ""
  },
  {
    "id": 88,
    "nick": "Burgess",
    "alive": false,
    "hp": 68,
    "power": 247,
    "def": 1,
    "att": 6,
    "farm": 13,
    "color": ""
  },
  {
    "id": 89,
    "nick": "Rasmussen",
    "alive": false,
    "hp": 80,
    "power": 1237,
    "def": 21,
    "att": 10,
    "farm": 6,
    "color": ""
  },
  {
    "id": 90,
    "nick": "Angeline",
    "alive": false,
    "hp": 34,
    "power": 236,
    "def": 0,
    "att": 22,
    "farm": 29,
    "color": ""
  },
  {
    "id": 91,
    "nick": "Brigitte",
    "alive": true,
    "hp": 61,
    "power": 1927,
    "def": 4,
    "att": 17,
    "farm": 21,
    "color": ""
  },
  {
    "id": 92,
    "nick": "Jeannine",
    "alive": false,
    "hp": 74,
    "power": 659,
    "def": 26,
    "att": 22,
    "farm": 7,
    "color": ""
  },
  {
    "id": 93,
    "nick": "Kerri",
    "alive": true,
    "hp": 50,
    "power": 354,
    "def": 19,
    "att": 14,
    "farm": 1,
    "color": ""
  },
  {
    "id": 94,
    "nick": "Sexton",
    "alive": false,
    "hp": 49,
    "power": 41,
    "def": 4,
    "att": 29,
    "farm": 21,
    "color": ""
  },
  {
    "id": 95,
    "nick": "Loretta",
    "alive": true,
    "hp": 46,
    "power": 1354,
    "def": 22,
    "att": 13,
    "farm": 11,
    "color": ""
  },
  {
    "id": 96,
    "nick": "Brandie",
    "alive": false,
    "hp": 50,
    "power": 1471,
    "def": 27,
    "att": 12,
    "farm": 29,
    "color": ""
  },
  {
    "id": 97,
    "nick": "Aileen",
    "alive": true,
    "hp": 45,
    "power": 2000,
    "def": 30,
    "att": 7,
    "farm": 24,
    "color": ""
  },
  {
    "id": 98,
    "nick": "Wise",
    "alive": true,
    "hp": 68,
    "power": 934,
    "def": 10,
    "att": 19,
    "farm": 5,
    "color": ""
  },
  {
    "id": 99,
    "nick": "Snow",
    "alive": true,
    "hp": 66,
    "power": 784,
    "def": 5,
    "att": 12,
    "farm": 7,
    "color": ""
  }
];