import { PlayerTile } from './playerTile';

export const PLAYERTILES: PlayerTile[] = [
  {
    "id": 0,
    "nick": "Víťa",
    "alive": false,
    "hp": 40,
    "power": 1076,
    "def": 0,
    "att": 9,
    "farm": 14,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 1,
    "nick": "Olda",
    "alive": true,
    "hp": 49,
    "power": 1474,
    "def": 6,
    "att": 18,
    "farm": 24,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 2,
    "nick": "Kryštof",
    "alive": true,
    "hp": 36,
    "power": 536,
    "def": 7,
    "att": 30,
    "farm": 22,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 3,
    "nick": "Tomáš",
    "alive": false,
    "hp": 54,
    "power": 453,
    "def": 6,
    "att": 5,
    "farm": 13,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 4,
    "nick": "☺",
    "alive": true,
    "hp": 54,
    "power": 818,
    "def": 22,
    "att": 7,
    "farm": 29,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 5,
    "nick": "Amber",
    "alive": true,
    "hp": 98,
    "power": 548,
    "def": 22,
    "att": 11,
    "farm": 26,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 6,
    "nick": "Rita",
    "alive": false,
    "hp": 85,
    "power": 567,
    "def": 19,
    "att": 8,
    "farm": 28,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 7,
    "nick": "Shields",
    "alive": true,
    "hp": 61,
    "power": 201,
    "def": 11,
    "att": 19,
    "farm": 21,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 8,
    "nick": "Suarez",
    "alive": true,
    "hp": 35,
    "power": 30,
    "def": 2,
    "att": 24,
    "farm": 19,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 9,
    "nick": "Douglas",
    "alive": false,
    "hp": 68,
    "power": 887,
    "def": 9,
    "att": 4,
    "farm": 1,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 10,
    "nick": "Huffman",
    "alive": false,
    "hp": 86,
    "power": 103,
    "def": 23,
    "att": 19,
    "farm": 11,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 11,
    "nick": "Laurie",
    "alive": true,
    "hp": 56,
    "power": 1679,
    "def": 9,
    "att": 28,
    "farm": 18,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 12,
    "nick": "Dalton",
    "alive": false,
    "hp": 60,
    "power": 1824,
    "def": 4,
    "att": 0,
    "farm": 15,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 13,
    "nick": "Maggie",
    "alive": true,
    "hp": 93,
    "power": 1575,
    "def": 0,
    "att": 13,
    "farm": 7,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 14,
    "nick": "Megan",
    "alive": true,
    "hp": 53,
    "power": 50,
    "def": 8,
    "att": 8,
    "farm": 21,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 15,
    "nick": "Albert",
    "alive": false,
    "hp": 39,
    "power": 942,
    "def": 7,
    "att": 7,
    "farm": 14,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 16,
    "nick": "Malone",
    "alive": false,
    "hp": 61,
    "power": 1007,
    "def": 15,
    "att": 0,
    "farm": 5,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 17,
    "nick": "Lancaster",
    "alive": true,
    "hp": 77,
    "power": 904,
    "def": 17,
    "att": 29,
    "farm": 10,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 18,
    "nick": "Bobbie",
    "alive": false,
    "hp": 99,
    "power": 301,
    "def": 2,
    "att": 9,
    "farm": 11,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 19,
    "nick": "Brittney",
    "alive": false,
    "hp": 32,
    "power": 1277,
    "def": 16,
    "att": 2,
    "farm": 16,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 20,
    "nick": "Gibson",
    "alive": true,
    "hp": 76,
    "power": 873,
    "def": 18,
    "att": 16,
    "farm": 15,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 21,
    "nick": "Latasha",
    "alive": true,
    "hp": 81,
    "power": 1682,
    "def": 6,
    "att": 16,
    "farm": 9,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 22,
    "nick": "Pacheco",
    "alive": false,
    "hp": 80,
    "power": 407,
    "def": 21,
    "att": 15,
    "farm": 16,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 23,
    "nick": "Rose",
    "alive": false,
    "hp": 45,
    "power": 1233,
    "def": 30,
    "att": 10,
    "farm": 25,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 24,
    "nick": "Carver",
    "alive": false,
    "hp": 65,
    "power": 1268,
    "def": 16,
    "att": 30,
    "farm": 10,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 25,
    "nick": "Angie",
    "alive": false,
    "hp": 97,
    "power": 1136,
    "def": 10,
    "att": 24,
    "farm": 16,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 26,
    "nick": "Webster",
    "alive": true,
    "hp": 91,
    "power": 1270,
    "def": 29,
    "att": 24,
    "farm": 9,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 27,
    "nick": "Wolfe",
    "alive": false,
    "hp": 81,
    "power": 1509,
    "def": 12,
    "att": 28,
    "farm": 10,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 28,
    "nick": "Bentley",
    "alive": false,
    "hp": 76,
    "power": 1903,
    "def": 10,
    "att": 17,
    "farm": 23,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 29,
    "nick": "Barr",
    "alive": true,
    "hp": 35,
    "power": 1983,
    "def": 13,
    "att": 28,
    "farm": 27,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 30,
    "nick": "Vega",
    "alive": true,
    "hp": 95,
    "power": 1519,
    "def": 6,
    "att": 30,
    "farm": 6,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 31,
    "nick": "Debbie",
    "alive": false,
    "hp": 78,
    "power": 583,
    "def": 10,
    "att": 16,
    "farm": 1,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 32,
    "nick": "Paula",
    "alive": false,
    "hp": 98,
    "power": 425,
    "def": 26,
    "att": 5,
    "farm": 21,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 33,
    "nick": "Mann",
    "alive": false,
    "hp": 44,
    "power": 599,
    "def": 4,
    "att": 20,
    "farm": 26,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 34,
    "nick": "Patton",
    "alive": true,
    "hp": 46,
    "power": 1418,
    "def": 23,
    "att": 12,
    "farm": 17,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 35,
    "nick": "Mccall",
    "alive": false,
    "hp": 45,
    "power": 1733,
    "def": 0,
    "att": 3,
    "farm": 16,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 36,
    "nick": "Augusta",
    "alive": true,
    "hp": 64,
    "power": 60,
    "def": 5,
    "att": 6,
    "farm": 5,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 37,
    "nick": "Gabrielle",
    "alive": false,
    "hp": 52,
    "power": 1469,
    "def": 26,
    "att": 12,
    "farm": 8,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 38,
    "nick": "Glover",
    "alive": false,
    "hp": 63,
    "power": 518,
    "def": 7,
    "att": 21,
    "farm": 14,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 39,
    "nick": "Elba",
    "alive": false,
    "hp": 59,
    "power": 1504,
    "def": 25,
    "att": 13,
    "farm": 8,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 40,
    "nick": "Ewing",
    "alive": true,
    "hp": 96,
    "power": 265,
    "def": 16,
    "att": 0,
    "farm": 4,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 41,
    "nick": "Finley",
    "alive": true,
    "hp": 46,
    "power": 194,
    "def": 23,
    "att": 26,
    "farm": 20,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 42,
    "nick": "Kristie",
    "alive": false,
    "hp": 46,
    "power": 600,
    "def": 10,
    "att": 10,
    "farm": 5,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 43,
    "nick": "Alfreda",
    "alive": false,
    "hp": 34,
    "power": 779,
    "def": 10,
    "att": 20,
    "farm": 11,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 44,
    "nick": "Karin",
    "alive": true,
    "hp": 97,
    "power": 1381,
    "def": 10,
    "att": 17,
    "farm": 19,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 45,
    "nick": "Meghan",
    "alive": true,
    "hp": 37,
    "power": 534,
    "def": 8,
    "att": 27,
    "farm": 15,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 46,
    "nick": "Carole",
    "alive": true,
    "hp": 99,
    "power": 258,
    "def": 24,
    "att": 0,
    "farm": 22,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 47,
    "nick": "Hurley",
    "alive": true,
    "hp": 76,
    "power": 503,
    "def": 26,
    "att": 27,
    "farm": 16,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 48,
    "nick": "Barnett",
    "alive": false,
    "hp": 95,
    "power": 1292,
    "def": 4,
    "att": 22,
    "farm": 1,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 49,
    "nick": "Heather",
    "alive": false,
    "hp": 94,
    "power": 0,
    "def": 3,
    "att": 1,
    "farm": 5,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 50,
    "nick": "Foster",
    "alive": true,
    "hp": 41,
    "power": 1496,
    "def": 7,
    "att": 14,
    "farm": 25,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 51,
    "nick": "Hudson",
    "alive": false,
    "hp": 69,
    "power": 997,
    "def": 29,
    "att": 26,
    "farm": 24,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 52,
    "nick": "Herminia",
    "alive": true,
    "hp": 74,
    "power": 1543,
    "def": 24,
    "att": 23,
    "farm": 30,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 53,
    "nick": "Rosa",
    "alive": true,
    "hp": 67,
    "power": 1670,
    "def": 25,
    "att": 13,
    "farm": 20,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 54,
    "nick": "Pearlie",
    "alive": true,
    "hp": 56,
    "power": 816,
    "def": 7,
    "att": 8,
    "farm": 17,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 55,
    "nick": "Rhoda",
    "alive": true,
    "hp": 53,
    "power": 1929,
    "def": 29,
    "att": 13,
    "farm": 2,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 56,
    "nick": "Delores",
    "alive": false,
    "hp": 62,
    "power": 995,
    "def": 28,
    "att": 13,
    "farm": 1,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 57,
    "nick": "Moon",
    "alive": true,
    "hp": 89,
    "power": 1009,
    "def": 3,
    "att": 13,
    "farm": 8,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 58,
    "nick": "Danielle",
    "alive": true,
    "hp": 64,
    "power": 950,
    "def": 25,
    "att": 13,
    "farm": 11,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 59,
    "nick": "Ethel",
    "alive": true,
    "hp": 58,
    "power": 1707,
    "def": 30,
    "att": 11,
    "farm": 8,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 60,
    "nick": "Preston",
    "alive": false,
    "hp": 52,
    "power": 898,
    "def": 6,
    "att": 11,
    "farm": 10,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 61,
    "nick": "Stark",
    "alive": true,
    "hp": 30,
    "power": 777,
    "def": 25,
    "att": 18,
    "farm": 6,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 62,
    "nick": "Mcdowell",
    "alive": false,
    "hp": 88,
    "power": 1861,
    "def": 1,
    "att": 27,
    "farm": 28,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 63,
    "nick": "Franks",
    "alive": true,
    "hp": 71,
    "power": 791,
    "def": 9,
    "att": 1,
    "farm": 2,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 64,
    "nick": "Sharlene",
    "alive": false,
    "hp": 32,
    "power": 706,
    "def": 9,
    "att": 26,
    "farm": 17,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 65,
    "nick": "Maude",
    "alive": false,
    "hp": 63,
    "power": 1479,
    "def": 1,
    "att": 21,
    "farm": 30,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 66,
    "nick": "Nellie",
    "alive": false,
    "hp": 64,
    "power": 216,
    "def": 21,
    "att": 13,
    "farm": 3,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 67,
    "nick": "Chase",
    "alive": false,
    "hp": 72,
    "power": 383,
    "def": 1,
    "att": 14,
    "farm": 7,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 68,
    "nick": "Mclaughlin",
    "alive": false,
    "hp": 81,
    "power": 1320,
    "def": 28,
    "att": 5,
    "farm": 10,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 69,
    "nick": "Parsons",
    "alive": true,
    "hp": 83,
    "power": 1516,
    "def": 6,
    "att": 17,
    "farm": 23,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 70,
    "nick": "Shelia",
    "alive": true,
    "hp": 36,
    "power": 1976,
    "def": 25,
    "att": 6,
    "farm": 11,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 71,
    "nick": "Harrison",
    "alive": true,
    "hp": 95,
    "power": 1030,
    "def": 21,
    "att": 13,
    "farm": 28,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 72,
    "nick": "Michelle",
    "alive": false,
    "hp": 95,
    "power": 1966,
    "def": 6,
    "att": 2,
    "farm": 11,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 73,
    "nick": "Myrtle",
    "alive": true,
    "hp": 51,
    "power": 258,
    "def": 26,
    "att": 30,
    "farm": 15,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 74,
    "nick": "Maxine",
    "alive": false,
    "hp": 63,
    "power": 1462,
    "def": 14,
    "att": 29,
    "farm": 16,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 75,
    "nick": "Louella",
    "alive": false,
    "hp": 92,
    "power": 276,
    "def": 1,
    "att": 7,
    "farm": 30,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 76,
    "nick": "Noreen",
    "alive": false,
    "hp": 70,
    "power": 1551,
    "def": 13,
    "att": 24,
    "farm": 25,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 77,
    "nick": "Sweeney",
    "alive": true,
    "hp": 50,
    "power": 1150,
    "def": 17,
    "att": 6,
    "farm": 16,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 78,
    "nick": "Joanne",
    "alive": true,
    "hp": 47,
    "power": 193,
    "def": 18,
    "att": 14,
    "farm": 17,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 79,
    "nick": "Hancock",
    "alive": false,
    "hp": 86,
    "power": 952,
    "def": 12,
    "att": 15,
    "farm": 15,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 80,
    "nick": "House",
    "alive": false,
    "hp": 61,
    "power": 482,
    "def": 3,
    "att": 5,
    "farm": 16,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 81,
    "nick": "Dionne",
    "alive": true,
    "hp": 75,
    "power": 262,
    "def": 7,
    "att": 9,
    "farm": 8,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 82,
    "nick": "Janelle",
    "alive": false,
    "hp": 67,
    "power": 1229,
    "def": 18,
    "att": 6,
    "farm": 0,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 83,
    "nick": "Melva",
    "alive": true,
    "hp": 54,
    "power": 752,
    "def": 27,
    "att": 30,
    "farm": 30,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 84,
    "nick": "Stephens",
    "alive": false,
    "hp": 70,
    "power": 320,
    "def": 27,
    "att": 5,
    "farm": 17,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 85,
    "nick": "Moore",
    "alive": false,
    "hp": 55,
    "power": 1297,
    "def": 3,
    "att": 20,
    "farm": 19,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 86,
    "nick": "Wynn",
    "alive": true,
    "hp": 37,
    "power": 143,
    "def": 15,
    "att": 19,
    "farm": 3,
    "color": "",
    "avatar_id": 5
  },
  {
    "id": 87,
    "nick": "Reese",
    "alive": false,
    "hp": 51,
    "power": 889,
    "def": 21,
    "att": 13,
    "farm": 25,
    "color": "",
    "avatar_id": 0
  },
  {
    "id": 88,
    "nick": "Tanisha",
    "alive": false,
    "hp": 85,
    "power": 1224,
    "def": 26,
    "att": 7,
    "farm": 1,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 89,
    "nick": "Jennie",
    "alive": false,
    "hp": 55,
    "power": 953,
    "def": 11,
    "att": 3,
    "farm": 11,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 90,
    "nick": "Lynette",
    "alive": true,
    "hp": 60,
    "power": 398,
    "def": 8,
    "att": 22,
    "farm": 8,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 91,
    "nick": "Bernard",
    "alive": false,
    "hp": 93,
    "power": 1490,
    "def": 24,
    "att": 22,
    "farm": 10,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 92,
    "nick": "Noble",
    "alive": false,
    "hp": 59,
    "power": 156,
    "def": 21,
    "att": 7,
    "farm": 22,
    "color": "",
    "avatar_id": 2
  },
  {
    "id": 93,
    "nick": "Bell",
    "alive": true,
    "hp": 94,
    "power": 1126,
    "def": 25,
    "att": 18,
    "farm": 0,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 94,
    "nick": "Witt",
    "alive": true,
    "hp": 80,
    "power": 1553,
    "def": 5,
    "att": 14,
    "farm": 9,
    "color": "",
    "avatar_id": 3
  },
  {
    "id": 95,
    "nick": "Elvia",
    "alive": true,
    "hp": 76,
    "power": 969,
    "def": 23,
    "att": 13,
    "farm": 29,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 96,
    "nick": "Elvira",
    "alive": true,
    "hp": 87,
    "power": 535,
    "def": 12,
    "att": 6,
    "farm": 11,
    "color": "",
    "avatar_id": 1
  },
  {
    "id": 97,
    "nick": "Therese",
    "alive": true,
    "hp": 47,
    "power": 1918,
    "def": 23,
    "att": 3,
    "farm": 9,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 98,
    "nick": "Morin",
    "alive": false,
    "hp": 40,
    "power": 26,
    "def": 21,
    "att": 13,
    "farm": 7,
    "color": "",
    "avatar_id": 4
  },
  {
    "id": 99,
    "nick": "Georgina",
    "alive": false,
    "hp": 93,
    "power": 1996,
    "def": 17,
    "att": 21,
    "farm": 4,
    "color": "",
    "avatar_id": 3
  }
];